### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by ZhaomingPsych** [catalystneuro/neuroconv#835]
### What happened?

I use Caiman to process my calcium imaging data, which is outputted as an HDF5 file. Unfortunately, I'm unable to convert larger datasets (480MB) to NWB format using the Neuroconv CaimanInterface, although it works fine with smaller datasets (40MB). I would like to understand why this is the case. Thank you!

### Steps to Reproduce

```python
from datetime import datetime
from dateutil import tz
from pathlib import Path
from neuroconv.datainterfaces import CaimanSegmentationInterface

file_path = r'F:\szbl\Data\Two-Photon\PC11\20240423\40X_1045_20min_results.hdf5'
interface = CaimanSegmentationInterface(file_path=file_path, verbose=False)

metadata = interface.get_metadata()
# For data provenance we add the time zone information to the conversion
session_start_time = datetime(2020, 1, 1, 12, 30, 0, tzinfo=tz.gettz("US/Pacific"))
metadata["NWBFile"].update(session_start_time=session_start_time)

# Choose a path for saving the nwb file and run the conversion
nwbfile_path = r'F:\szbl\Data\Two-Photon\PC11\20240423\40X_1045_20min_results.nwb'
interface.run_conversion(nwbfile_path=nwbfile_path, metadata=metadata)
```

### Traceback

```python
IndexError                                Traceback (most recent call last)
c:\Users\ZhaoMing\Documents\CaImAn-1.10.9\CaImAn-1.10.9\demos\notebooks\demo_pipeline.ipynb Cell 132 line 7
      4 from neuroconv.datainterfaces import CaimanSegmentationInterface
      6 file_path = r'F:\szbl\Data\Two-Photon\PC11\20240423\40X_1045_20min_results.hdf5'
----> 7 interface = CaimanSegmentationInterface(file_path=file_path, verbose=False)
      9 metadata = interface.get_metadata()
     10 # For data provenance we add the time zone information to the conversion

File b:\Anaconda3\envs\caiman\lib\site-packages\neuroconv\datainterfaces\ophys\caiman\caimandatainterface.py:22, in CaimanSegmentationInterface.__init__(self, file_path, verbose)
     12 def __init__(self, file_path: FilePathType, verbose: bool = True):
     13     """
     14 
     15     Parameters
   (...)
     20         Whether to print progress
     21     """
---> 22     super().__init__(file_path=file_path)
     23     self.verbose = verbose

File b:\Anaconda3\envs\caiman\lib\site-packages\neuroconv\datainterfaces\ophys\basesegmentationextractorinterface.py:23, in BaseSegmentationExtractorInterface.__init__(self, **source_data)
     21 def __init__(self, **source_data):
     22     super().__init__(**source_data)
---> 23     self.segmentation_extractor = self.get_extractor()(**source_data)
...
    135                     for i in range(len(slice_))]
    137 slice_shape = ()
    138 int_index = ()

IndexError: tuple index out of range
Output is truncated. View as a scrollable element or open in a text editor. Adjust cell output settings...
```

### Operating System

Windows

### Python Executable

Conda

### Python Version

3.10

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by CodyCBakerPhD** [comment]
A couple of things to try

i) We just refactored Caiman yesterday and that version hasn't been released yet - can you try to make a fresh conda environment and do `pip install git+https://github.com/catalystneuro/neuroconv.git@main` (will need `conda install git` or `pip install gitpython` to do the direct installation via `git`)

Then try again and let us know if you get the same error

ii) The `Output is truncated. View as a scrollable element or open in a text editor. Adjust cell output settings...` is limiting how much I can diagnose at a glance of the traceback - can you try copying that code snippet for the interface into a file named `test_caiman_nwb.py` file and run the file as a script with `python test_caiman_nwb.py`? That should printout the entire trace, which can allow us to dig a bit deeper

iii) If all else fails, we'd probably ask you to share the file in question and then we can see about reproducing and fixing on our end - Google Drive, Dropbox, etc. all work well for that

cc @pauladkisson

**Comment by ZhaomingPsych** [comment]
Thank you for your reply! 1) I try to use Conda install a new enviorment, and follow your direction to install other package. When I run the above code, a error occur: `---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[2], [line 2](vscode-notebook-cell:?execution_count=2&line=2)
      [1](vscode-notebook-cell:?execution_count=2&line=1) file_path = r'E:\ZM\Two-photon\PC11\20240423\40X_1045_20min_results.hdf5'
----> [2](vscode-notebook-cell:?execution_count=2&line=2) interface = CaimanSegmentationInterface(file_path=file_path, verbose=False)

File d:\Anaconda3\envs\neuroncov\lib\site-packages\neuroconv\datainterfaces\ophys\caiman\caimandatainterface.py:22, in CaimanSegmentationInterface.__init__(self, file_path, verbose)
     [12](file:///D:/Anaconda3/envs/neuroncov/lib/site-packages/neuroconv/datainterfaces/ophys/caiman/caimandatainterface.py:12) def __init__(self, file_path: FilePathType, verbose: bool = True):
     [13](file:///D:/Anaconda3/envs/neuroncov/lib/site-packages/neuroconv/datainterfaces/ophys/caiman/caimandatainterface.py:13)     """
     [14](file:///D:/Anaconda3/envs/neuroncov/lib/site-packages/neuroconv/datainterfaces/ophys/caiman/caimandatainterface.py:14) 
     [15](file:///D:/Anaconda3/envs/neuroncov/lib/site-packages/neuroconv/datainterfaces/ophys/caiman/caimandatainterface.py:15)     Parameters
   (...)
     [20](file:///D:/Anaconda3/envs/neuroncov/lib/site-packages/neuroconv/datainterfaces/ophys/caiman/caimandatainterface.py:20)         Whether to print progress
     [21](file:///D:/Anaconda3/envs/neuroncov/lib/site-packages/neuroconv/datainterfaces/ophys/caiman/caimandatainterface.py:21)     """
---> [22](file:///D:/Anaconda3/envs/neuroncov/lib/site-packages/neuroconv/datainterfaces/ophys/caiman/caimandatainterface.py:22)     super().__init__(file_path=file_path)
     [23](file:///D:/Anaconda3/envs/neuroncov/lib/site-packages/neuroconv/datainterfaces/ophys/caiman/caimandatainterface.py:23)     self.verbose = verbose

File d:\Anaconda3\envs\neuroncov\lib\site-packages\neuroconv\datainterfaces\ophys\basesegmentationextractorinterface.py:23, in BaseSegmentationExtractorInterface.__init__(self, **source_data)
     [21](file:///D:/Anaconda3/envs/neuroncov/lib/site-packages/neuroconv/datainterfaces/ophys/basesegmentationextractorinterface.py:21) def __init__(self, **source_data):
     [22](file:///D:/Anaconda3/envs/neuroncov/lib/site-packages/neuroconv/datainterfaces/ophys/basesegmentationextractorinterface.py:22)     super().__init__(**source_data)
---> [23](file:///D:/Anaconda3/envs/neuroncov/lib/site-packages/neuroconv/datainterfaces/ophys/basesegmentationextractorinterface.py:23)     self.segmentation_extractor = self.get_extractor()(**source_data)

File d:\Anaconda3\envs\neuroncov\lib\site-packages\neuroconv\baseextractorinterface.py:25, in BaseExtractorInterface.get_extractor(cls)
     [23](file:///D:/Anaconda3/envs/neuroncov/lib/site-packages/neuroconv/baseextractorinterface.py:23) if cls.Extractor is not None:
     [24](file:///D:/Anaconda3/envs/neuroncov/lib/site-packages/neuroconv/baseextractorinterface.py:24)     return cls.Extractor
---> [25](file:///D:/Anaconda3/envs/neuroncov/lib/site-packages/neuroconv/baseextractorinterface.py:25) extractor_module = get_package(package_name=cls.ExtractorModuleName)
     [26](file:///D:/Anaconda3/envs/neuroncov/lib/site-packages/neuroconv/baseextractorinterface.py:26) extractor = getattr(
     [27](file:///D:/Anaconda3/envs/neuroncov/lib/site-packages/neuroconv/baseextractorinterface.py:27)     extractor_module,
     [28](file:///D:/Anaconda3/envs/neuroncov/lib/site-packages/neuroconv/baseextractorinterface.py:28)     cls.ExtractorName or cls.__name__.replace("Interface", "Extractor"),
     [29](file:///D:/Anaconda3/envs/neuroncov/lib/site-packages/neuroconv/baseextractorinterface.py:29) )
     [30](file:///D:/Anaconda3/envs/neuroncov/lib/site-packages/neuroconv/baseextractorinterface.py:30) cls.Extractor = extractor

File d:\Anaconda3\envs\neuroncov\lib\site-packages\neuroconv\tools\importing.py:123, in get_package(package_name, installation_instructions, excluded_python_versions, excluded_platforms_and_python_versions)
    [120](file:///D:/Anaconda3/envs/neuroncov/lib/site-packages/neuroconv/tools/importing.py:120)     return sys.modules[package_name]
    [122](file:///D:/Anaconda3/envs/neuroncov/lib/site-packages/neuroconv/tools/importing.py:122) if is_package_installed(package_name=package_name) is not None:
--> [123](file:///D:/Anaconda3/envs/neuroncov/lib/site-packages/neuroconv/tools/importing.py:123)     return import_module(name=package_name)
    [125](file:///D:/Anaconda3/envs/neuroncov/lib/site-packages/neuroconv/tools/importing.py:125) raise ModuleNotFoundError(
    [126](file:///D:/Anaconda3/envs/neuroncov/lib/site-packages/neuroconv/tools/importing.py:126)     f"\nThe required package'{package_name}' is not installed!\n"
    [127](file:///D:/Anaconda3/envs/neuroncov/lib/site-packages/neuroconv/tools/importing.py:127)     f"To install this package, please run\n\n\t{installation_instructions}\n"
    [128](file:///D:/Anaconda3/envs/neuroncov/lib/site-packages/neuroconv/tools/importing.py:128) )

File d:\Anaconda3\envs\neuroncov\lib\importlib\__init__.py:126, in import_module(name, package)
    [124](file:///D:/Anaconda3/envs/neuroncov/lib/importlib/__init__.py:124)             break
    [125](file:///D:/Anaconda3/envs/neuroncov/lib/importlib/__init__.py:125)         level += 1
--> [126](file:///D:/Anaconda3/envs/neuroncov/lib/importlib/__init__.py:126) return _bootstrap._gcd_import(name[level:], package, level)

File <frozen importlib._bootstrap>:1050, in _gcd_import(name, package, level)

File <frozen importlib._bootstrap>:1027, in _find_and_load(name, import_)

File <frozen importlib._bootstrap>:1004, in _find_and_load_unlocked(name, import_)

ModuleNotFoundError: No module named 'roiextractors'`

**Comment by CodyCBakerPhD** [comment]
> ModuleNotFoundError: No module named 'roiextractors'`

Can you run `pip install roiextractors` in the fresh environment

**Comment by ZhaomingPsych** [comment]
When I run `pip install roiextractors`, the error changes to `tuple index out of range`. I try to write a script `test_caiman_nwb.py` to run the fresh environment, the error still exists.

`(neuroncov) PS C:\Users\jianglab\Documents\CaImAn-1.9.16\demos\general> python test_caiman_nwb.py
Traceback (most recent call last):
  File "C:\Users\jianglab\Documents\CaImAn-1.9.16\demos\general\test_caiman_nwb.py", line 7, in <module>
    interface = CaimanSegmentationInterface(file_path=file_path, verbose=False)
  File "D:\Anaconda3\envs\neuroncov\lib\site-packages\neuroconv\datainterfaces\ophys\caiman\caimandatainterface.py", line 22, in __init__
    super().__init__(file_path=file_path)
  File "D:\Anaconda3\envs\neuroncov\lib\site-packages\neuroconv\datainterfaces\ophys\basesegmentationextractorinterface.py", line 23, in __init__
    self.segmentation_extractor = self.get_extractor()(**source_data)
  File "D:\Anaconda3\envs\neuroncov\lib\site-packages\roiextractors\extractors\caiman\caimansegmentationextractor.py", line 59, in __init__
    self._roi_response_dff = self._trace_extractor_read("F_dff")
  File "D:\Anaconda3\envs\neuroncov\lib\site-packages\roiextractors\extractors\caiman\caimansegmentationextractor.py", line 130, in _trace_extractor_read
    return lazy_ops.DatasetView(self._dataset_file["estimates"][field]).lazy_transpose()
  File "D:\Anaconda3\envs\neuroncov\lib\site-packages\lazy_ops\lazy_loading.py", line 46, in __new__
    dsetview = DatasetViewh5py(dataset=dataset)
  File "D:\Anaconda3\envs\neuroncov\lib\site-packages\lazy_ops\lazy_loading.py", line 69, in __init__
    self._shape, self._key, self._int_index, self._axis_order = self._slice_shape(slice_index)
  File "D:\Anaconda3\envs\neuroncov\lib\site-packages\lazy_ops\lazy_loading.py", line 133, in _slice_shape
    slice_regindices = [slice(*slice_[i].indices(self.dataset.shape[self.axis_order[i]])) if isinstance(slice_[i],slice)
  File "D:\Anaconda3\envs\neuroncov\lib\site-packages\lazy_ops\lazy_loading.py", line 133, in <listcomp>
    slice_regindices = [slice(*slice_[i].indices(self.dataset.shape[self.axis_order[i]])) if isinstance(slice_[i],slice)
IndexError: tuple index out of range`

**Comment by CodyCBakerPhD** [comment]
Thanks for the full traceback

My goodness, haven't seen a `lazy_ops` bug in a long time

What do you think @pauladkisson? Should we try to minimally reproduce and raise an issue up at that level or refactor the Caiman side in ROIExtractors to bypass `lazy_ops`?

**Comment by ZhaomingPsych** [comment]
3. I have uploaded my file to Google Drive. Maybe you can try to run it on your end! Thank you for your time and attention!
https://drive.google.com/file/d/12k6453WI-wUYN6W3xks2LWHpUV-Nzn9R/view?usp=sharing

**Comment by CodyCBakerPhD** [comment]
> I have uploaded my file to Google Drive. Maybe you can try to run it on your end! Thank you for your time and attention!

Thanks!

@pauladkisson I noticed in the file they shared the `F_dff` looks a bit odd - any ideas? Ever seen this? Maybe we should ping Eric on this one too

![image](https://github.com/catalystneuro/neuroconv/assets/51133164/2bd1c684-cb33-454e-8701-bf9e0ae9525f)

**Comment by ZhaomingPsych** [comment]
Hello, I resolved the issue by changing the code release version from 1.10.9 to 1.9.16, and now everything is working fine. I noticed that the hdf5 file shape differs between versions 1.10.9 and 1.9.16. Do you know why?

**Comment by CodyCBakerPhD** [comment]
Good to hear!

> I resolved the issue by changing the code release version from 1.10.9 to 1.9.16

The code release version of what package?

**Comment by ZhaomingPsych** [comment]
Sorry to reply now, I used _demo_pipeline.ipynb_ from 1.9.16
