### ISSUE TITLE
[Bug]: Object of type `LabMetaDataExtension` is not JSON serializable

### ISSUE THREAD

**Issue by tabedzki** [catalystneuro/neuroconv#891]
### What happened?

I am save a custom `.mat` matlab data file using nwb extension called tank-lab-to-nwb  ([repo](https://github.com/catalystneuro/tank-lab-to-nwb)) that uses the ndx-tank-metadata ([repo](https://github.com/catalystneuro/ndx-tank-metadata), [pip](https://pypi.org/project/ndx-tank-metadata/)) on github. 

I am able to properly load in example .mat data and add the information to an empty in-memory nwbfile by doing
```python
from pynwb.testing.mock.file import mock_NWBFile
empty_nwb = mock_NWBFile()
interface.add_to_nwbfile(empty_nwb, metadata = metadata)
````
where interface is the custom VirmenDataInterface from the tank_lab_to_nwb repo. 

The alternative of `interface.create_nwbfile(metadata = metadata)` also safely creates an in-memory NWB file. The error comes when I execute `interface.run_conversion(nwbfile_path="./fdf13.nwb", metadata = metadata, overwrite=True)` , I end up with the error below.

Some useful information about the variables in question. 

@CodyCBakerPhD  since you had worked on this previously, do you have an idea of which variable type this might be failing?

The `obj` value when the code fails 

```python
obj
LabMetaData abc.LabMetaDataExtension at 0x5790013840
Fields:
  commit_id: 3611d165cf09db453e272b63e3f460cb95d3c10f New stationary task, copy velocity-position
  experiment_name: jessejorge_pwm_v2
  location: 165I-miniVR-T-6
  mazes: mazes <class 'ndx_tank_metadata.maze_extension.MazeExtension'>
  num_trials: 200
  protocol_name: pwm_jessejorge_v2
  rig: rig abc.RigExtension at 0x5790020608
Fields:
  arduinoPort: COM6
  ballCircumference: 63.8
  colorAdjustment: [0.  0.4 0.5]
  hasDAQ: 1
  hasSyncComm: 0
  laserChannel: 3
  leftPuffChannel: 1
  minIterationDT: 0.01
  nidaqDevice: 1
  nidaqLines: [ 0 11]
  nidaqPort: 0
  rewardChannel: 0
  rewardDuration: 0.025
  rewardSize: 0.004
  rig: 165I-miniVR-T-6
  rightPuffChannel: 2
  sensorDotsPerRev: [2310.1 2310.1 2310.1 2310.1]
  simulationMode: 0
  soundAdjustment: 0.2
  syncClockChannel: 5
  syncDataChannel: 6
  toroidXFormP1: 0.3879
  toroidXFormP2: 0.392

  session_end_time: 2024-03-22T12:09:54.779000
  stimulus_bank_path: C:\Experiments\ViRMEn\experiments\protocols\stimulus_trains_pwm_jessejorge_v2.mat
  world_file_name: jessejorge_pwm_v2
```

```python
obj.mazes
mazes ndx_tank_metadata.maze_extension.MazeExtension at 0x5790015136
Fields:
  colnames: ['world' 'lStart' 'lCue' 'lMemory' 'cueDuration' 'cueVisibleAt'
 'cueProbability' 'cueDensityPerM' 'antiFraction' 'nCueSlots'
 'tri_turnHint' 'color' 'numTrials' 'numTrialsPerMin' 'criteriaNTrials'
 'warmupNTrials' 'numSessions' 'performance' 'maxBias' 'warmupMaze'
 'warmupPerform' 'warmupBias' 'warmupMotor' 'easyBlock' 'easyBlockNTrials'
 'numBlockTrials' 'blockPerform']
  columns: (
    world <class 'hdmf.common.table.VectorData'>,
    lStart <class 'hdmf.common.table.VectorData'>,
    lCue <class 'hdmf.common.table.VectorData'>,
    lMemory <class 'hdmf.common.table.VectorData'>,
    cueDuration <class 'hdmf.common.table.VectorData'>,
    cueVisibleAt <class 'hdmf.common.table.VectorData'>,
    cueProbability <class 'hdmf.common.table.VectorData'>,
    cueDensityPerM <class 'hdmf.common.table.VectorData'>,
    antiFraction <class 'hdmf.common.table.VectorData'>,
    nCueSlots <class 'hdmf.common.table.VectorData'>,
    tri_turnHint <class 'hdmf.common.table.VectorData'>,
    color <class 'hdmf.common.table.VectorData'>,
    numTrials <class 'hdmf.common.table.VectorData'>,
    numTrialsPerMin <class 'hdmf.common.table.VectorData'>,
    criteriaNTrials <class 'hdmf.common.table.VectorData'>,
    warmupNTrials <class 'hdmf.common.table.VectorData'>,
    numSessions <class 'hdmf.common.table.VectorData'>,
    performance <class 'hdmf.common.table.VectorData'>,
    maxBias <class 'hdmf.common.table.VectorData'>,
    warmupMaze <class 'hdmf.common.table.VectorData'>,
    warmupPerform <class 'hdmf.common.table.VectorData'>,
    warmupBias <class 'hdmf.common.table.VectorData'>,
    warmupMotor <class 'hdmf.common.table.VectorData'>,
    easyBlock <class 'hdmf.common.table.VectorData'>,
    easyBlockNTrials <class 'hdmf.common.table.VectorData'>,
    numBlockTrials <class 'hdmf.common.table.VectorData'>,
    blockPerform <class 'hdmf.common.table.VectorData'>
  )
  description: description of the mazes
  id: id <class 'hdmf.common.table.ElementIdentifiers'
```

```python
obj.rig
rig abc.RigExtension at 0x5790020608
Fields:
  arduinoPort: COM6
  ballCircumference: 63.8
  colorAdjustment: [0.  0.4 0.5]
  hasDAQ: 1
  hasSyncComm: 0
  laserChannel: 3
  leftPuffChannel: 1
  minIterationDT: 0.01
  nidaqDevice: 1
  nidaqLines: [ 0 11]
  nidaqPort: 0
  rewardChannel: 0
  rewardDuration: 0.025
  rewardSize: 0.004
  rig: 165I-miniVR-T-6
  rightPuffChannel: 2
  sensorDotsPerRev: [2310.1 2310.1 2310.1 2310.1]
  simulationMode: 0
  soundAdjustment: 0.2
  syncClockChannel: 5
  syncDataChannel: 6
  toroidXFormP1: 0.3879
  toroidXFormP2: 0.392
```

### Steps to Reproduce

```python
# %% The script used to get this bug
"""Author: Christian"""
# from tank_lab_to_nwb import VirmenDataInterface
import sys
import os
sys.path.append(os.getcwd())
print(os.getcwd())

from pathlib import Path
from isodate import duration_isoformat
from datetime import timedelta, datetime

import neuroconv

from tank_lab_to_nwb.convert_towers_task.virmenbehaviordatainterface import VirmenDataInterface



# %%
base_path = Path("/Users/ct5868/code/tank-lab-to-nwb/")
virmen_file_path = base_path / "behavior_local" / "jessejorge_pwm_jessejorge_pwm_pilot_165I-miniVR-T-6_jyanar_ya011_T_20240322.mat"


interface = VirmenDataInterface(file_path = virmen_file_path)

# %%
metadata = interface.get_metadata()
print(metadata)

# %%
metadata["Subject"] = dict(
    subject_id="M001",
    sex="M",
    age="P30D",
    species="Mus musculus",
)


# %%
interface.get_metadata_schema()

# %%
from datetime import datetime
from zoneinfo import ZoneInfo

metadata["NWBFile"]["session_start_time"] = datetime(2021, 1, 1, 12, 0, 0, tzinfo=ZoneInfo("US/Pacific"))

# %%
interface.get_metadata_schema()

# %%
from pynwb.testing.mock.file import mock_NWBFile
empty_nwb = mock_NWBFile()

print(metadata)


# %%


interface.create_nwbfile(metadata = metadata)
interface.run_conversion(nwbfile_path="./mariokart.nwb", metadata = metadata, overwrite=True)
# interface.run_conversion(nwbfile_path="./fdf13.nwb", metadata = metadata, overwrite=True)

# %%
```

### Traceback

```python
Exception has occurred: TypeError
Object of type LabMetaDataExtension is not JSON serializable
  File "/Users/ct5868/code/neuroconv/src/neuroconv/utils/json_schema.py", line 34, in default
    return super().default(obj)
  File "/Users/ct5868/code/neuroconv/src/neuroconv/utils/json_schema.py", line 350, in validate_metadata
    serialized_metadata = encoder.encode(metadata)
  File "/Users/ct5868/code/neuroconv/src/neuroconv/tools/nwb_helpers/_metadata_and_file_helpers.py", line 70, in make_nwbfile_from_metadata
    validate_metadata(metadata=metadata, schema=base_metadata_schema)
  File "/Users/ct5868/code/neuroconv/src/neuroconv/tools/nwb_helpers/_metadata_and_file_helpers.py", line 231, in make_or_load_nwbfile
    raise e
  File "/Users/ct5868/code/neuroconv/src/neuroconv/tools/nwb_helpers/_metadata_and_file_helpers.py", line 231, in make_or_load_nwbfile
    raise e
  File "/Users/ct5868/code/neuroconv/src/neuroconv/basedatainterface.py", line 167, in run_conversion
    with make_or_load_nwbfile(
  File "/Users/ct5868/code/tank-lab-to-nwb/notebooks/attempting behavior datainterfaces--debugging.py", line 62, in <module>
    interface.run_conversion(nwbfile_path="./mariokart.nwb", metadata = metadata, overwrite=True)
TypeError: Object of type LabMetaDataExtension is not JSON serializable
LabMetaData
```

### Operating System

Windows

### Python Executable

Conda

### Python Version

3.10

### Package Versions

[environment_for_issue.txt](https://github.com/user-attachments/files/15742688/environment_for_issue.txt)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by tabedzki** [comment]
An an update, if you run `interface.create_nwbfile(metadata=metdata)` twice
```python
interface.create_nwbfile(metadata=metdata)
interface.create_nwbfile(metadata=metdata)
```
then you get a similar error stack

```python
{
	"name": "TypeError",
	"message": "Object of type LabMetaDataExtension is not JSON serializable",
	"stack": "---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[63], line 2
      1 interface.create_nwbfile(metadata = metadata)
----> 2 interface.create_nwbfile(metadata = metadata)
      3 # interface.run_conversion(nwbfile_path=\"./fdf13.nwb\", metadata = metadata, overwrite=True)

File ~/code/neuroconv/src/neuroconv/basedatainterface.py:96, in BaseDataInterface.create_nwbfile(self, metadata, **conversion_options)
     93 if metadata is None:
     94     metadata = self.get_metadata()
---> 96 nwbfile = make_nwbfile_from_metadata(metadata=metadata)
     97 self.add_to_nwbfile(nwbfile=nwbfile, metadata=metadata, **conversion_options)
     99 return nwbfile

File ~/code/neuroconv/src/neuroconv/tools/nwb_helpers/_metadata_and_file_helpers.py:70, in make_nwbfile_from_metadata(metadata)
     68 schema_path = Path(__file__).resolve().parent.parent.parent / \"schemas\" / \"base_metadata_schema.json\"
     69 base_metadata_schema = load_dict_from_file(file_path=schema_path)
---> 70 validate_metadata(metadata=metadata, schema=base_metadata_schema)
     72 nwbfile_kwargs = deepcopy(metadata[\"NWBFile\"])
     73 # convert ISO 8601 string to datetime

File ~/code/neuroconv/src/neuroconv/utils/json_schema.py:350, in validate_metadata(metadata, schema, verbose)
    347 encoder = NWBMetaDataEncoder()
    348 # The encoder produces a serialized object, so we deserialized it for comparison
--> 350 serialized_metadata = encoder.encode(metadata)
    351 decoded_metadata = json.loads(serialized_metadata)
    352 validate(instance=decoded_metadata, schema=schema)

File /opt/anaconda3/envs/neuroconv3.10/lib/python3.10/json/encoder.py:199, in JSONEncoder.encode(self, o)
    195         return encode_basestring(o)
    196 # This doesn't pass the iterator directly to ''.join() because the
    197 # exceptions aren't as detailed.  The list call should be roughly
    198 # equivalent to the PySequence_Fast that ''.join() would do.
--> 199 chunks = self.iterencode(o, _one_shot=True)
    200 if not isinstance(chunks, (list, tuple)):
    201     chunks = list(chunks)

File /opt/anaconda3/envs/neuroconv3.10/lib/python3.10/json/encoder.py:257, in JSONEncoder.iterencode(self, o, _one_shot)
    252 else:
    253     _iterencode = _make_iterencode(
    254         markers, self.default, _encoder, self.indent, floatstr,
    255         self.key_separator, self.item_separator, self.sort_keys,
    256         self.skipkeys, _one_shot)
--> 257 return _iterencode(o, 0)

File ~/code/neuroconv/src/neuroconv/utils/json_schema.py:34, in NWBMetaDataEncoder.default(self, obj)
     31     return obj.tolist()
     33 # The base-class handles it
---> 34 return super().default(obj)

File /opt/anaconda3/envs/neuroconv3.10/lib/python3.10/json/encoder.py:179, in JSONEncoder.default(self, o)
    160 def default(self, o):
    161     \"\"\"Implement this method in a subclass such that it returns
    162     a serializable object for ``o``, or calls the base implementation
    163     (to raise a ``TypeError``).
   (...)
    177 
    178     \"\"\"
--> 179     raise TypeError(f'Object of type {o.__class__.__name__} '
    180                     f'is not JSON serializable')

TypeError: Object of type LabMetaDataExtension is not JSON serializable"
}
```


If I skip the`interface.create_nwbfile(metadata=metdata)` and go straight to `interface.run_conversion(nwbfile_path="./mariokart.nwb", metadata = metadata, overwrite=True)`, then I get a following error

```python
{
	"name": "ZeroDivisionError",
	"message": "division by zero",
	"stack": "---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
Cell In[54], line 2
      1 # interface.create_nwbfile(metadata = metadata)
----> 2 interface.run_conversion(nwbfile_path=\"./fdf13.nwb\", metadata = metadata, overwrite=True)

File ~/code/neuroconv/src/neuroconv/basedatainterface.py:179, in BaseDataInterface.run_conversion(self, nwbfile_path, nwbfile, metadata, overwrite, backend, backend_configuration, **conversion_options)
    176     self.add_to_nwbfile(nwbfile=nwbfile_out, metadata=metadata, **conversion_options)
    178 if backend_configuration is None:
--> 179     backend_configuration = self.get_default_backend_configuration(nwbfile=nwbfile_out, backend=backend)
    181 configure_backend(nwbfile=nwbfile_out, backend_configuration=backend_configuration)

File ~/code/neuroconv/src/neuroconv/basedatainterface.py:206, in BaseDataInterface.get_default_backend_configuration(nwbfile, backend)
    183 @staticmethod
    184 def get_default_backend_configuration(
    185     nwbfile: NWBFile,
   (...)
    188     backend: Literal[\"hdf5\"] = \"hdf5\",
    189 ) -> Union[HDF5BackendConfiguration, ZarrBackendConfiguration]:
    190     \"\"\"
    191     Fill and return a default backend configuration to serve as a starting point for further customization.
    192 
   (...)
    204         The default configuration for the specified backend type.
    205     \"\"\"
--> 206     return get_default_backend_configuration(nwbfile=nwbfile, backend=backend)

File ~/code/neuroconv/src/neuroconv/tools/nwb_helpers/_backend_configuration.py:19, in get_default_backend_configuration(nwbfile, backend)
     16 \"\"\"Fill a default backend configuration to serve as a starting point for further customization.\"\"\"
     18 BackendConfigurationClass = BACKEND_CONFIGURATIONS[backend]
---> 19 return BackendConfigurationClass.from_nwbfile(nwbfile=nwbfile)

File ~/code/neuroconv/src/neuroconv/tools/nwb_helpers/_configuration_models/_base_backend.py:61, in BackendConfiguration.from_nwbfile(cls, nwbfile)
     58 @classmethod
     59 def from_nwbfile(cls, nwbfile: NWBFile) -> Self:
     60     default_dataset_configurations = get_default_dataset_io_configurations(nwbfile=nwbfile, backend=cls.backend)
---> 61     dataset_configurations = {
     62         default_dataset_configuration.location_in_file: default_dataset_configuration
     63         for default_dataset_configuration in default_dataset_configurations
     64     }
     66     return cls(dataset_configurations=dataset_configurations)

File ~/code/neuroconv/src/neuroconv/tools/nwb_helpers/_configuration_models/_base_backend.py:61, in <dictcomp>(.0)
     58 @classmethod
     59 def from_nwbfile(cls, nwbfile: NWBFile) -> Self:
     60     default_dataset_configurations = get_default_dataset_io_configurations(nwbfile=nwbfile, backend=cls.backend)
---> 61     dataset_configurations = {
     62         default_dataset_configuration.location_in_file: default_dataset_configuration
     63         for default_dataset_configuration in default_dataset_configurations
     64     }
     66     return cls(dataset_configurations=dataset_configurations)

File ~/code/neuroconv/src/neuroconv/tools/nwb_helpers/_dataset_configuration.py:127, in get_default_dataset_io_configurations(nwbfile, backend)
    124         if isinstance(column, TimeSeriesReferenceVectorData):
    125             continue
--> 127         dataset_io_configuration = DatasetIOConfigurationClass.from_neurodata_object(
    128             neurodata_object=column, dataset_name=\"data\"
    129         )
    131         yield dataset_io_configuration
    132 elif isinstance(neurodata_object, NWBContainer):

File ~/code/neuroconv/src/neuroconv/tools/nwb_helpers/_configuration_models/_base_dataset_io.py:272, in DatasetIOConfiguration.from_neurodata_object(cls, neurodata_object, dataset_name)
    270     compression_method = \"gzip\"
    271 elif dtype != np.dtype(\"object\"):
--> 272     chunk_shape = SliceableDataChunkIterator.estimate_default_chunk_shape(
    273         chunk_mb=10.0, maxshape=full_shape, dtype=np.dtype(dtype)
    274     )
    275     buffer_shape = SliceableDataChunkIterator.estimate_default_buffer_shape(
    276         buffer_gb=0.5, chunk_shape=chunk_shape, maxshape=full_shape, dtype=np.dtype(dtype)
    277     )
    278     compression_method = \"gzip\"

File ~/code/neuroconv/src/neuroconv/tools/hdmf.py:38, in GenericDataChunkIterator.estimate_default_chunk_shape(chunk_mb, maxshape, dtype)
     35 chunk_bytes = chunk_mb * 1e6
     37 min_maxshape = min(maxshape)
---> 38 v = tuple(math.floor(maxshape_axis / min_maxshape) for maxshape_axis in maxshape)
     39 prod_v = math.prod(v)
     40 while prod_v * itemsize > chunk_bytes and prod_v != 1:

File ~/code/neuroconv/src/neuroconv/tools/hdmf.py:38, in <genexpr>(.0)
     35 chunk_bytes = chunk_mb * 1e6
     37 min_maxshape = min(maxshape)
---> 38 v = tuple(math.floor(maxshape_axis / min_maxshape) for maxshape_axis in maxshape)
     39 prod_v = math.prod(v)
     40 while prod_v * itemsize > chunk_bytes and prod_v != 1:

ZeroDivisionError: division by zero"
}
```

**Comment by CodyCBakerPhD** [comment]
OK, sorry it took a bit to get back on this. A lot is going in with the issues-within-issues

The first thing is which script is 'most proper' to the usual workflow NeuroConv supports. The parred down version of this would be

```python
from pathlib import Path
from datetime import datetime
from zoneinfo import ZoneInfo

from tank_lab_to_nwb.convert_towers_task.virmenbehaviordatainterface import VirmenDataInterface

base_path = Path("/Users/ct5868/code/tank-lab-to-nwb/")
virmen_file_path = base_path / "behavior_local" / "jessejorge_pwm_jessejorge_pwm_pilot_165I-miniVR-T-6_jyanar_ya011_T_20240322.mat"

interface = VirmenDataInterface(file_path = virmen_file_path)

metadata = interface.get_metadata()
metadata["Subject"] = dict(
    subject_id="M001",
    sex="M",
    age="P30D",
    species="Mus musculus",
)
metadata["NWBFile"]["session_start_time"] = datetime(2021, 1, 1, 12, 0, 0, tzinfo=ZoneInfo("US/Pacific"))

interface.run_conversion(nwbfile_path="./mariokart.nwb", metadata = metadata, overwrite=True)
```

Now, the core most issue in this thread is the `ZeroDivisionError` during auotmatic backend configuration

I'll get a fix started and ping you when the dev branch is ready to try

The rest of the issues are indicative to me of `metadata` mutation problems (`metadata should never mutate the object during `add_to_nwbfile` - we avoid this in our tools by making a `deepcopy` of the dictionary prior to modifying it in any downstream code

I suspect this because of your difference in earlier error behavior after calling `create_nwbfile` first and then calling it twice

`LabMetadata` in particular is not a part of the core NeuroConv metadata so I know that's the only way it might be getting there - that said, if the interface does actually intend to have that field, then you'll have to modify the `metadata_schema` (just a JSON schema) to accept that property at the outer level

**Comment by tabedzki** [comment]
I want to just recap what the problem was: there were fields in some of the matlab structs that were empty (e.g., `struct.field = []` so then we were converted that, it was recorded as a `np.array([], dtype=unit8)` which has a len of 0 and was causing some incompatibilities when concatenating with integers. Therefore, to resolve that, I ended up changing the `metadata` for those empty structs to be recorded as nans (I inserted it after this [line](https://github.com/catalystneuro/tank-lab-to-nwb/blob/932d49f18f722c880d2ee5e1ecf0fd68dab3a3b1/tank_lab_to_nwb/convert_towers_task/virmenbehaviordatainterface.py#L66-L67)



```python
# Original for loop used to handle np.nan
for maze in experiment_metadata["mazes"]:
    for k, v in maze["criteria"].items():
        if k.startswith('warmup') and isinstance(v, np.ndarray) and len(v) == 0:
            maze["criteria"][k] = np.nan

# Updated comprehension to not use explicit for loop
for maze in experiment_metadata["mazes"]:
    maze["criteria"].update({k: np.nan for k, v in maze["criteria"].items() if k.startswith('warmup') and isinstance(v, np.ndarray) and len(v) == 0})
```

> The rest of the issues are indicative to me of metadata mutation problems (metadata should never mutate the object during add_to_nwbfile- we avoid this in our tools by making a deepcopy` of the dictionary prior to modifying it in any downstream code
>
> I suspect this because of your difference in earlier error behavior after calling create_nwbfile first and then calling it twice
> 
> LabMetadata in particular is not a part of the core NeuroConv metadata so I know that's the only way it might be getting there - that said, if the interface does actually intend to have that field, then you'll have to modify the metadata_schema (just a JSON schema) to accept that property at the outer level


When you say that we should not be modifying the `metadata` and that you make a deep copy of the dictionary, is the example code above (and the code in the github link) an example of what should not be done? If so, what would be the appropriate variation?  

Thanks in advance

**Comment by CodyCBakerPhD** [comment]
If `experiment_metadata` is the thing getting passed in the end to `converter.run_conversion`, then there are two approaches

i) put that code you have for NaN handling into the `get_metadata` function for that interface, such that the returned initial base metadata is the corrected form. It does not need to be mutated after this point

ii) If this code exists in the `add_to_nwbfile` stage (this is the stage we do not want to mutate passed arguments except the `nwbfile`) set `metadata_copy = copy.deepcopy(metadata)` then do all that NaN handling to the `metadata_copy` instead

**Comment by tabedzki** [comment]
Okay, so I verified the code and there is code that exists that appends to metadata but nothing that takes the original `metadata` based in and changes the previous existing values. Is that something that is permitted by design? 


Snippet from `add_to_nwbfile`
```python
            lab_meta_data = dict(
                name='LabMetaData',
                experiment_name=converted_metadata[
                    'experiment_name'] if 'experiment_name' in converted_metadata else '',
                world_file_name=experiment_metadata['name'],
                protocol_name=converted_metadata[
                    'protocol_name'] if 'protocol_name' in converted_metadata else '',
                stimulus_bank_path=subject_metadata['stimulusBank'] if subject_metadata[
                    'stimulusBank'] else '',
                commit_id=experiment_metadata['repository'],
                location=experiment_metadata['rig']['rig'],
                num_trials=num_trials,
                session_end_time=session_end_time,
                rig=rig_extension,
                mazes=maze_extension,
                # session_performance=0.,  # comment out to add (not in behavior file)
            )
            metadata['lab_meta_data'] = LabMetaDataExtension(**lab_meta_data)
```

**Comment by CodyCBakerPhD** [comment]
To help I'd have to see a line reference to that snippet

Keep in mind that  Python is all pass by reference for this kind of stuff too (pointers) so it can be easily hidden by aliasing

**Comment by tabedzki** [comment]
Hi Cody, here is a fork the `tank-lab-to-nwb` extension. These [lines](https://github.com/tabedzki/tank-lab-to-nwb/blob/6f5f654496fe6ac90429d3eef5b8ff1bd6caf710/tank_lab_to_nwb/convert_towers_task/virmenbehaviordatainterface.py#L113-L134) were the only ones where I saw any direct manipulation of the metadata.

---
Unrelated question, when those changes are ready to be made, should I overwrite the copy hosted on pip, and if so, how do I get write permissions from y'all?

**Comment by CodyCBakerPhD** [comment]
Looks like only @bendichter and @weiglszonja are owners on PyPI for https://pypi.org/project/tank-lab-to-nwb/ and https://pypi.org/project/ndx-tank-metadata/, so they'd have to get your PyPI username to add you there

**Comment by CodyCBakerPhD** [comment]
Yes, line https://github.com/tabedzki/tank-lab-to-nwb/blob/6f5f654496fe6ac90429d3eef5b8ff1bd6caf710/tank_lab_to_nwb/convert_towers_task/virmenbehaviordatainterface.py#L133 is exactly what I'm talking about

The `metadata` dictionary passed into the `add_to_nwbfile` function is later modified (by adding that key/value for lab metadata); it should be copied, or that line should belong to `get_metadata` if possible (unsure at a glance if it relies on information parsed only elsewhere within `add_to_nwbfile`

**Comment by CodyCBakerPhD** [comment]
The easiest solution would just be to set `metadata_copy = copy.deepcopy(metadata)` right before line https://github.com/tabedzki/tank-lab-to-nwb/blob/6f5f654496fe6ac90429d3eef5b8ff1bd6caf710/tank_lab_to_nwb/convert_towers_task/virmenbehaviordatainterface.py#L61 and then swap all references in `add_to_nwbfile` to use `metadata_copy` instead
