### ISSUE TITLE
[Bug]: No module named 'packaging'

### ISSUE THREAD

**Issue by rly** [catalystneuro/neuroconv#903]
### What happened?

Reported by a user using the code below after a clean install of "neuroconv[tiff]" on Linux. I could reproduce after a clean install of "neuroconv" on Mac M1 on both Python 3.9 and 3.10.

### Steps to Reproduce

```python
#### Traceback from user
$ conda create --name tye_to_nwb_lee_matthews python=3.9 -y
$ conda activate tye_to_nwb_lee_matthews
$ pip install neuroconv[tiff]
$ pip install -U pynwb
$ python

Python 3.9.19 | packaged by conda-forge | (main, Mar 20 2024, 12:50:21)
[GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import json
>>> from datetime import datetime
>>> from zoneinfo import ZoneInfo
>>> from pathlib import Path
>>> from neuroconv.datainterfaces import TiffImagingInterface


#### MWE from me
conda create --name test python=3.9 --yes
conda activate test
pip install neuroconv
python -c "import neuroconv"
```

### Traceback

```python
#### From user

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lkeyes/.local/lib/python3.9/site-packages/neuroconv/__init__.py", line 1, in <module>
    from .basedatainterface import BaseDataInterface
  File "/home/lkeyes/.local/lib/python3.9/site-packages/neuroconv/basedatainterface.py", line 12, in <module>
    from .tools.nwb_helpers import (
  File "/home/lkeyes/.local/lib/python3.9/site-packages/neuroconv/tools/__init__.py", line 3, in <module>
    from .importing import (
  File "/home/lkeyes/.local/lib/python3.9/site-packages/neuroconv/tools/importing.py", line 11, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'

#### From me

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/rly/mambaforge/envs/test/lib/python3.9/site-packages/neuroconv/__init__.py", line 1, in <module>
    from .basedatainterface import BaseDataInterface
  File "/Users/rly/mambaforge/envs/test/lib/python3.9/site-packages/neuroconv/basedatainterface.py", line 12, in <module>
    from .tools.nwb_helpers import (
  File "/Users/rly/mambaforge/envs/test/lib/python3.9/site-packages/neuroconv/tools/__init__.py", line 3, in <module>
    from .importing import (
  File "/Users/rly/mambaforge/envs/test/lib/python3.9/site-packages/neuroconv/tools/importing.py", line 11, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'
```

### Operating System

macOS

### Python Executable

Conda

### Python Version

3.9

### Package Versions

[environment_for_issue.txt](https://github.com/user-attachments/files/15811834/environment_for_issue.txt)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by h-mayorquin** [comment]
This should be solved by https://github.com/catalystneuro/neuroconv/pull/904
